# adapted from:
# https://gist.github.com/jonatasbaldin/b0eba2ac8ee887ca27ee811697d4d73b#file-poetry_and_circleci-yml
version: 2

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      # if the text key `deps-{{ checksum "poetry.lock" }}` changes (and it WILL
      # change everytime poetry.lock is updated since we rely on its checksum)
      # and pyproject.toml is updated every time we add a new dependency to our project
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
      # Install the dependencies
      - run:
          name: Install Dependencies
          command: |
            curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
            poetry install --no-root
      # If you don't install anything new, this folder won't change and the cache will be effective
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
      # And send our coverage somewhere, in this case, coveralls
      - run:
          name: Run Pytest, report coverage
          command: |
            poetry run make test-cov
            poetry run codecov --token $CODECOV_TOKEN

workflows:
  version: 2
  build-and-test-workflow:
    jobs:
      - build-and-test
